<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeBehind="Terminos.aspx.cs" Inherits="WebVideo.Registro" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Cuerpo" runat="server">
    <strong><span style="font-size: large">Términos de uso de Hookin</span></strong><br />

            <p>Hookin es un servicio de suscripción que permite a nuestros suscriptores acceder a películas y series de TV (A partir de ahora, contenido de Hookin) mediante streaming a través de Internet a determinados aparatos de televisión, ordenadores y otros dispositivos con conexión a Internet (A partir de ahora, dispositivos compatibles con Hookin").</p><br />

            <p>El servicio Hookin te lo proporciona Hookin Holding & asociados, una sociedad de responsabilidad limitada de los España. Estos Términos de uso rigen tu uso de nuestro servicio. A los efectos de estos Términos de uso, "servicio Hookin", "nuestro servicio" o "el servicio" significan el servicio que presta Hookin para encontrar y ver contenido de Hookin, incluidas todas sus características y funcionalidades, recomendaciones y reseñas, el sitio web e interfaces de usuario, así como todos los contenidos y software asociados a nuestro servicio.</p><br />

            <strong>1. Suscripción.</strong><br />
            <p>Tu suscripción a Hookin continuará mes a mes hasta su terminación. Para utilizar el servicio Hookin debes tener acceso a Internet y un dispositivo compatible con Netflix, y facilitarnos un método de pago aceptado, válido y vigente, que puedes actualizar cuando lo consideres oportuno ("Método de pago"). A menos que canceles tu suscripción con anterioridad a la fecha de facturación mensual, nos autorizas a cargar la cuota de suscripción correspondiente al siguiente mes en tu Método de pago (consulta "Cancelación" más adelante). Puedes encontrar detalles específicos acerca de tu suscripción a Hookin visitando nuestro sitio web y haciendo clic en el enlace "Tu cuenta" disponible en la parte superior de las páginas del sitio web Hookin bajo tu nombre de perfil.</p><br />
            <strong>2. Facturación</strong><br />
            <strong>2.1. Ciclo de facturación.</strong><br style="font-weight: 700" />
            <p>La cuota de suscripción al servicio Hookin y cualesquiera otros cargos asociados a tu uso del mismo, como impuestos y potenciales tarifas de transacción, se facturarán mensualmente a tu Método de pago el día natural que corresponda al inicio de la porción de pago de tu suscripción. En algunos casos la fecha de facturación puede cambiar, como por ejemplo si tu Método de pago no se ha configurado correctamente o si tu suscripción de pago se inició en un día no existente en un mes determinado. Visita nuestro sitio web y haz clic en el enlace "Datos de facturación" en la página "Tu cuenta" para consultar la fecha de tu próximo pago.</p><br />
            <strong>2.2. Métodos de pago.</strong><br />
            <p>Puedes cambiar tu Método de pago visitando nuestro sitio web y haciendo clic en el enlace "Tu cuenta". Si el pago no se configura correctamente, debido a caducidad, insuficiencia de fondos, o por alguna otra razón, y no cambias tu Método de pago o cancelas tu cuenta, podemos suspender tu acceso al servicio hasta que obtengamos un Método de pago válido. Cuando actualices tu Método de pago, nos autorizas a continuar facturando al Método de pago actualizado y seguirás siendo responsable de cualquier cantidad no cobrada. Esto puede implicar un cambio en las fechas de pago de tus facturas. El emisor de algunos Métodos de pago puede cobrarte ciertas tarifas, como por ejemplo por operación en moneda extranjera u otros cargos relacionados con el procesamiento de tu Método de pago. Los cargos por impuestos locales pueden variar dependiendo del Método de pago usado. Consulta con tu proveedor de servicio de Método de pago para obtener detalles.</p><br />
            <strong>2.3. Cancelación.</strong><br />
            <p>Puedes cancelar tu suscripción de Hookin en cualquier momento, y seguirás teniendo acceso al servicio Hookin hasta el final de tu periodo de facturación mensual. En la medida en que lo permita la ley, los pagos no son reembolsables y no facilitamos devoluciones ni abonos por periodos parciales de suscripción mensual o contenido de Hookin no visionado. Para cancelar tu suscripción, ve a la página "Tu cuenta" y sigue las instrucciones para la cancelación. Si cancelas tu suscripción, tu cuenta se cerrará automáticamente al final de tu presente periodo de facturación. Para ver cuando se cerrará tu cuenta, haz clic en "Datos de facturación" en la página "Tu cuenta". Si te inscribiste en Hookin usando tu cuenta con un tercero como Método de pago y deseas cancelar tu suscripción a Hookin, es posible que tengas que hacerlo a través de dicho tercero. Por ejemplo, puede que tengas que visitar tu cuenta en el correspondiente tercero y desactivar la renovación automática del servicio Hookin, o darte de baja de este, a través de dicho tercero. También puedes obtener información sobre facturación de tu suscripción a Hookin visitando tu cuenta en el correspondiente tercero.</p><br />
            <strong>2.4. Cambios de precio y de los planes de servicio.</strong><br />
            <p>Podemos cambiar nuestros planes de servicio y su precio cuando lo consideremos oportuno. Sin embargo, ningún cambio de precio o de los planes de servicio te afectará hasta pasados 30 días desde que te lo notifiquemos.</p><br />
            <strong>3. Servicio Hookin</strong><br />
            <p>3.1. Debes tener 18 años de edad, o ser mayor de edad en tu provincia, territorio o país, para poder suscribirte al servicio Hookin. Los menores de edad solo pueden utilizar el servicio bajo la supervisión de un adulto.</p><br />
            <p>3.2. El servicio Hookin y cualquier contenido visionado a través del servicio son exclusivamente para tu uso personal y no para uso comercial. Durante tu suscripción a Hookin, te concedemos una licencia limitada, no exclusiva e intransferible, para acceder al servicio Hookin y ver contenido de Hookin. A excepción de la precedente licencia limitada, no se te transferirá ningún derecho, título o interés. Aceptas no utilizar el servicio para exhibiciones públicas.</p><br />
            <p>3.3. Puedes ver el contenido de Hookin principalmente dentro del país en el que hayas establecido tu cuenta y solo en las ubicaciones geográficas donde ofrezcamos nuestro servicio y hayamos licenciado dichos contenidos. El contenido disponible para visionado varía en función de la ubicación geográfica y cambia periódicamente. El número de dispositivos en que puedes visionar simultáneamente depende del plan de suscripción por el que hayas optado y se concreta en la página "Tu cuenta".</p><br />
            <p>3.4. Hookin realiza cambios en el servicio con regularidad, incluida la biblioteca de contenidos. Además, analizamos continuamente varios aspectos de nuestro servicio, incluido nuestro sitio web, las interfaces de usuario, las funciones promocionales y la disponibilidad del contenido de Hookin. En cualquier momento puedes excluir los análisis visitando la página "Tu cuenta" y cambiando la configuración de "Participación en pruebas".</p><br />
            <p>3.5. Parte del contenido de Hookin está disponible para su descarga temporal y el visionado sin conexión en determinados dispositivos compatibles ("Títulos offline"). Existen ciertas limitaciones, incluyendo restricciones del número de Títulos offline por cuenta, el número máximo de dispositivos que pueden contener Títulos offline, el periodo de tiempo que tienes para empezar a ver Títulos offline y por cuánto tiempo serán accesibles los Títulos offline. Es posible que ciertos Títulos offline no puedan reproducirse en determinados países, y que si te conectas en un país en el que no pudieras ver ese Título offline en streaming, dicho Título offline no se podrá reproducir mientras estés en ese país.</p><br />
            <p>3.6. Aceptas usar el servicio Hookin, incluidas todas sus opciones y funciones asociadas, de acuerdo con la legislación vigente, normativa y reglamentos, u otras limitaciones de uso del servicio o contenido allí previstas. Aceptas no archivar, reproducir, distribuir, modificar, exhibir, ejecutar, publicar, licenciar, crear trabajos derivados, poner a la venta, o (salvo lo autorizado de modo expreso en estos Términos de uso) usar contenidos o información contenida en el servicio Hookin u obtenidos a través de él o en él. También aceptas no burlar, eliminar, alterar, desactivar, rebajar o impedir ninguna de las protecciones de contenido del servicio Hookin; no usar ningún robot, spider, scraper u otros medios automáticos para acceder al servicio Hookin; no descompilar, hacer ingeniería inversa o desmontar ningún programa informático u otros productos o procesos accesibles desde el servicio Hookin; no introducir ningún código o producto o manipular los contenidos del servicio Hookin de ninguna manera; y no usar ningún método de búsqueda, recopilación o extracción de datos. Además, aceptas no subir, publicar, enviar por correo electrónico o transmitir por ningún otro medio ningún material diseñado para interrumpir, destruir o limitar la funcionalidad de ningún software, hardware o equipo de telecomunicaciones asociado al servicio Hookin, como por ejemplo virus informáticos u otros códigos de ordenador, archivos o programas. Podemos resolver o restringir tu uso de nuestro servicio si infringes estos Términos de uso o si incurres en uso ilegal o fraudulento del servicio.</p><br />
            <p>3.7. La calidad de exhibición del contenido de Hookin puede variar en función del dispositivo, y puede verse afectada por diversos factores, como tu ubicación, el ancho de banda disponible y/o la velocidad de tu conexión a Internet. La disponibilidad de Alta Definición (en adelante HD, High Definition), Ultra Alta Definición (en adelante Ultra HD) y alto rango dinámico (en adelante HDR) dependerá de tu servicio de Internet y de las prestaciones de tu dispositivo. No todos los contenidos están disponibles en todos los formatos, como HD, Ultra HD o HDR, y no todos los planes de suscripción te permiten recibir contenidos en todos los formatos. La configuración de reproducción predeterminada en redes de telefonía móvil excluye el contenido en HD, Ultra HD y HDR. La velocidad mínima de conexión para calidad estándar (en adelante SD, Standard Definition) es de 0,5 Mbps. Sin embargo, recomendamos una mayor velocidad para una mejor calidad de vídeo. Se recomienda una velocidad de descarga de al menos 5 Mbps por stream para recibir contenido en HD (definida como una resolución igual o superior a 720p). Se recomienda una velocidad de descarga de al menos 25 Mbps por stream para recibir contenido en Ultra HD (definida como una resolución igual o superior a 1080p) y HDR. Eres responsable de todos los cargos por conexión a Internet. Comprueba con tu proveedor de Internet la información sobre posibles cargos por uso de datos de Internet. El tiempo que tarda en empezar a verse el contenido de Netflix varía en función de varios factores, entre otros tu ubicación, el ancho de banda disponible en ese momento, el contenido que hayas seleccionado y la configuración de tu dispositivo compatible con Hookin.</p><br />
            <p>3.8. El software de Hookin ha sido desarrollado por Hookin y está diseñado para permitir el visionado de contenido de Hookin mediante dispositivos compatibles con Hookin. El software de Hookin puede variar según el dispositivo y el medio, y sus funciones pueden también diferir entre dispositivos. Reconoces que el uso del servicio puede requerir software de terceros sujeto a licencias de dichos terceros. Aceptas que podrías recibir de modo automático versiones actualizadas del software de Hookin y de terceros relacionados.</p><br />
            <strong>4. Contraseña y acceso a la cuenta.</strong><br />
            <p>El suscriptor que haya creado la cuenta de Hookin y cuyo Método de pago sea cargado (el "Titular de la cuenta") tiene acceso a la cuenta de Hookin y control sobre ella así como de los dispositivos compatibles con Hookin utilizados para acceder a nuestro servicio. Para mantener el control sobre la cuenta y evitar que cualquiera acceda a ella (que incluiría información sobre el historial de visionado de la cuenta), el Titular de la cuenta deberá mantener el control de todos los dispositivos compatibles con Hookin que se usen para acceder al servicio y no revelar a nadie ni la contraseña ni los detalles del Método de pago asociados a dicha cuenta. Eres responsable de actualizar y mantener la veracidad de la información que nos facilites acerca de tu cuenta. Podemos cancelar tu cuenta o bloquearla para protegerte a ti, a Hookin o a nuestros asociados de usurpación de identidad o de otra actividad fraudulenta.</p><br />
            <strong>5. Disposiciones varias</strong><br />
            5.1. Legislación aplicable.<br />
            <p>Estos Términos de uso se regirán e interpretarán de acuerdo con la legislación de España. Estos términos no limitarán ninguna protección al consumidor a la que puedas tener derecho conforme a la legislación vigente en tu país de residencia.</p><br />
            <strong>5.2. Materiales no solicitados.</strong><br />
            <p>Hookin no acepta materiales no solicitados ni ideas para contenido de Hookin, y no se hace responsable del parecido de ninguno de sus contenidos o programación en ningún medio con materiales o ideas enviados a Hookin.</p><br />
            <strong>5.3. Atención al cliente.</strong><br />
            <p>Para obtener más información sobre nuestro servicio y sus opciones, o si necesitas ayuda con tu cuenta, visita la página de Preguntas Frecuentes de Hookin en nuestro sitio web (www.hookin.com/faq). En determinados casos, el Servicio de atención al cliente puede prestarte una mejor asistencia mediante una herramienta de soporte de acceso remoto a través de la cual tenemos pleno acceso a tu ordenador. Si no deseas que dispongamos de este acceso, deberás no consentir la asistencia a través de la herramienta de acceso remoto, en cuyo caso te atenderemos por otros medios. Estos Términos de uso tendrán prioridad en caso de conflicto entre ellos y la información proporcionada por el Servicio de atención al cliente u otros apartados de nuestro sitio web.</p><br />
            <strong>5.4. Subsistencia.</strong><br />
            <p>Si alguna disposición o disposiciones de estos Términos de uso fueran declaradas inválidas, ilegales o inaplicables, dicha circunstancia no afectará la validez, legalidad y aplicabilidad de las disposiciones restantes que permanecerán en plena vigencia y efecto.</p><br />
            <strong>5.5. Cambios de los Términos de uso.</strong><br />
            <p>Hookin puede cambiar estos Términos de uso cuando lo considere oportuno. Te notificaremos por lo menos 30 días antes de que los nuevos Términos de uso te sean de aplicación.</p><br />
            <strong>5.6. Comunicaciones electrónicas.</strong><br />
            <p>Te enviaremos información acerca de tu cuenta (como autorizaciones de pago, facturas, cambios en la contraseña o en el Método de pago, mensajes de confirmación, avisos) únicamente en formato electrónico, por ejemplo a través de correo electrónico a la dirección proporcionada durante el proceso de registro.</p><br />

            Última actualización: 27/04/2018<br />
</asp:Content>

